app/app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('tldr.urls', namespace='tldr')),
    url(r'^admin/', include(admin.site.urls)),
)

app/tldr/urls.py
from django.conf.urls import patterns, url
from tldr import views

urlpatterns = patterns('',

    url(r'^$', views.index, name='index'),
	url(r'^summarize/$', views.summarize, name='summarize'),
	url(r'^summary/$', views.summary, name='summary'),
	url(r'^summary_api/$', views.summary_api, name='summary_api'),
	url(r'^api_result/$', views.api_result, name='api_result') 
)

app/tldr/models.py
from django.db import models

app/tldr/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
#from tldr.utils import PageRankSummarizer, LuhnSummarizer, KeyPhraseSummarizer, CommunitySummarizer, ArticleExtractor, CombinedSummarizer
from tldr.utils import KeyPhraseSummarizer, ArticleExtractor, CombinedSummarizer
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    return render(request, 'tldr/index.html', {})

def summarize(request):
	if 'news_article' not in request.POST or len(request.POST['news_article']) < 1 :
		return render(request, 'tldr/index.html', { 'error_message': "News article is empty or mostly contains stop words." })
	else:
		news_article = request.POST['news_article']
		news_article = ArticleExtractor.filter_unicode(news_article)
		summary = CombinedSummarizer.summarize(news_article);
		request.session['summary'] = summary
		return HttpResponseRedirect(reverse('tldr:summary', args=()))

def summary(request):
	if 'summary' not in request.session:
		return render(request, 'tldr/index.html', { 'error_message': 'Session Expired!!' })
	else:
		summary = request.session['summary']
		del request.session['summary']
		return render(request, 'tldr/summary.html', { 'summary': summary })

@csrf_exempt
def summary_api(request):
	if 'url' not in request.POST or len(request.POST['url']) < 1 :
		return HttpResponse('No news article to summarize!!')
	else:
		url = request.POST['url']
		news_article = ArticleExtractor.parse(url)
		summary = CombinedSummarizer.summarize(news_article['text']);
		request.session['title'] = news_article['headline']
		request.session['summary'] = summary
		return HttpResponseRedirect(reverse('tldr:api_result', args=()))

def api_result(request):
	if 'summary' not in request.session:
		return HttpResponse('Session expired!!')
	else:
		summary = request.session['summary']

		s = '~'.join(summary)
		t = request.session['title']

		del request.session['summary']
		del request.session['title']

		return HttpResponse(t + '@' + s)

app/tldr/templates/tldr/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
	    <!-- Meta, title, CSS, favicons, etc. -->
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="TLDR News Summarizer">
		<meta name="keywords" content="News article summarizer, Speech and Natural Language Processing">
		<!-- <meta name="author" content="Group 6"> -->

		<!-- Bootstrap core CSS -->
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
		<!-- Custom CSS -->
		<!-- <link href="{% static 'tldr/css/style.css' %}" rel="stylesheet"> -->
		<style>
			body { 
				padding-top: 70px;
			}	
		</style>
		<title>
			TLDR News
		</title>
	</head>

	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
			    <div class="navbar-header">
			      <button id="toggle_button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'tldr:index' %}" >TLDR: News Article Summarizer</a>
			    </div>

			    <div class="collapse navbar-collapse" id="navbar-collapse">
			      <ul class="nav navbar-nav navbar-right">
			      <li id="about_item" class=""><a id="about" onclick="$('#aboutModal').modal()" href="#">Team</a></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

		<!-- Modal -->
		<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="aboutModalLabel">TLDR News Summarizer</h4>
		      </div>
		      <div class="modal-body">
		        <b>Developed by:</b>
		       <p>
		        	<ul>
		        		<li><h6>Abhishek Pant</h6></li>
		        		<li><h6>Aniruddha Gupta</h6></li>
		        		<li><h6>Ankit Jain</h6></li>
		        		<li><h6>Bhaskar Bagchi</h6></li>
		        		<li><h6>Rishi Rajiv Mehta</h6></li>
		        		<li><h6>Shushman Chowdhary</h6></li>		        		
		        		<li><h6>Utkarsh Jaiswal</h6></li>	        		
		        	</ul>
		        </p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="container">
			{% if error_message %}<div class="well"><strong>{{ error_message }}</strong></div>{% endif %}
			<form class="form-horizontal" role="form" action="{% url 'tldr:summarize' %}" method="post">
			{% csrf_token %}
				<div class="form-group">
					<label for="input_news_article" class="col-sm-2 control-label">News article:</label>
					<div class="col-sm-10">
						<textarea id="input_news_article" name="news_article" class="form-control" rows="20"></textarea>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
					  <button type="submit" class="btn btn-default">Summarize</button>
					</div>
				</div>
			</form>
		</div><!-- /.container -->
		<hr>
		<div class="container">
			<footer>
				<b>Speech and Natural Language Processing, Department of Computer Science and Engineering, IIT Kharagpur</b>
			</footer>
		</div>
		<!-- JQuery core javascript  -->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<!-- Bootstrap core JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	</body>
</html>

app/tldr/templates/tldr/summary.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
	    <!-- Meta, title, CSS, favicons, etc. -->
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="TLDR News Summarizer">
		<meta name="keywords" content="News article summarizer, Speech and Natural Language Processing">
		<!-- <meta name="author" content="Group 6"> -->

		<!-- Bootstrap core CSS -->
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
		<!-- Custom CSS -->
		<!-- <link href="{% static 'tldr/css/style.css' %}" rel="stylesheet"> -->
		<style>
			body { 
				padding-top: 70px;
			}	
		</style>
		<title>
			TLDR News
		</title>
	</head>

	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
			    <div class="navbar-header">
			      <button id="toggle_button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'tldr:index' %}" >TLDR: News Article Summarizer</a>
			    </div>

			    <div class="collapse navbar-collapse" id="navbar-collapse">
			      <ul class="nav navbar-nav navbar-right">
			      <li id="about_item" class=""><a id="about" onclick="$('#aboutModal').modal()" href="#">Team</a></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

		<!-- Modal -->
		<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="aboutModalLabel">TLDR News Summarizer</h4>
		      </div>
		      <div class="modal-body">
		        <b>Developed by:</b>
		       <p>
		        	<ul>
		        		<li><h6>Abhishek Pant</h6></li>
		        		<li><h6>Aniruddha Gupta</h6></li>
		        		<li><h6>Ankit Jain</h6></li>
		        		<li><h6>Bhaskar Bagchi</h6></li>
		        		<li><h6>Rishi Rajiv Mehta</h6></li>
		        		<li><h6>Shushman Chowdhary</h6></li>		        		
		        		<li><h6>Utkarsh Jaiswal</h6></li>
		        	</ul>
		        </p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="container">
			<label >Generated Summary:</label>
			<div id="output_summary" class="well">
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
				<ul>
				{% if summary %}
					{% for s in summary %}
					    <li>{{ s }}</li>
					{% endfor %}
				{% endif %}
				</ul>
			</div>
		</div><!-- /.container -->
		<hr>
		<div class="container">
			<footer>
				<b>Speech and Natural Language Processing, Department of Computer Science and Engineering, IIT Kharagpur</b>
			</footer>
		</div>

		<!-- JQuery core javascript  -->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<!-- Bootstrap core JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	</body>
</html>
	